# 1. The Database URL (Tells Spring to look on your local computer for 'showroom_db')
spring.datasource.url=jdbc:mysql://localhost:3306/showroom_db

# 2. Your MySQL Username (It is almost always 'root' on a local machine)
spring.datasource.username=root

# 3. Your MySQL Password (Replace this with your real password!)
spring.datasource.password=Root@2026

# 4. The Magic Hibernate Command (Auto-builds the tables)
spring.jpa.hibernate.ddl-auto=update

# Optional: Shows the SQL commands in your VS Code terminal 
spring.jpa.show-sql=true


# Turn ON specific endpoints
management.endpoints.web.exposure.include=metrics,info

# Turn everything ON
management.endpoints.web.exposure.include=*

# Turn specific ones OFF (even if included above)
management.endpoints.web.exposure.exclude=info

